### ISSUE TITLE
isError set to false on type mismatch

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-core#108]
While using the openlaw-client we are seeing that `isError === false` when there is a type mismatch.

See: https://github.com/openlawteam/openlaw/issues/2226

**Comment by adridadou** [comment]
Could u add an example of a template with the error? So I can reproduce

**Comment by jtrein** [comment]
@jdville03 wrote it inside the referenced issue above in openlaw app.

**Comment by adridadou** [comment]
this has been fixed in develop!
