### ISSUE TITLE
Refactor error handling to remove thrown exceptions

### ISSUE THREAD

**Issue by craigwblake-openlaw** [openlawteam/openlaw-core#130]
Currently much of the error handling is done through thrown exceptions.  There are many areas where we could eliminate throw exceptions either by refining types to eliminate exceptional cases, or by using Result for explicit error handling.

**Comment by outkaj** [comment]
this has been merged right? @craigwblake-openlaw

**Comment by craigwblake-openlaw** [comment]
Yes, good catch.  There are still a few places where we are throwing exceptions, particularly in the parser, but makes sense to close this out.
