### ISSUE TITLE
Formatting bug when typing a small, decimal amount

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-core#134]
When typing a small, decimal amount into a `Number` input (e.g. `.0002`) the formatting appears to be wrong, as it inserts a comma. I've never seen this type of formatting before, so I could be wrong about the possible bug.

<img width="431" alt="Screen Shot 2019-05-14 at 10 04 58 AM" src="https://user-images.githubusercontent.com/1144320/57670648-ee982680-762f-11e9-87e1-8c9aa5597997.png">

**Comment by adridadou** [comment]
created a PR for that

**Comment by jtrein** [comment]
Handled via #154
