### ISSUE TITLE
OpenLaw API user uploading contract is unable to call certain API functions

### ISSUE THREAD

**Issue by joshma91** [openlawteam/openlaw-core#141]
### Issue
The OpenLaw API user is unable to call certain API functions (e.g. `loadContractStatus` and `getContract`) when a contract (submitted by the API user) has signatories differing from the OpenLaw API user.

### Steps to reproduce
Reproduction repo here: https://github.com/joshma91/ol-bug-reprod (based off of the OpenLaw API Tutorial repo from Michael Rice). Note that the OpenLaw API user is **openlawdummy@gmail.com**

1. `git clone https://github.com/joshma91/ol-bug-reprod.git`
2. `npm install`
3. `npm run start`
4. at localhost:3000, filling out the form as follows and submitting allows for `apiClient.loadContractStatus(contractId)` to be successfully called (note the console output @ App.js:232 showing the contract status)

![image](https://user-images.githubusercontent.com/9612111/58232372-33862200-7cee-11e9-811e-dfd81f762233.png)

What's important here is that one of the signatory emails is the API user openlawdummy@gmail.com. Any ethereum address can be used in the address fields.

5. reloading and filling out the form again **without** the API user as below throws an error when `apiClient.loadContractStatus(contractId)` is called

![image](https://user-images.githubusercontent.com/9612111/58232432-51538700-7cee-11e9-9858-d92e71fe0d1c.png)

### Observed behaviour
The OpenLaw API user is only able to successfully call the function `loadContractStatus` when the API user is one of the signatories. When the API user is not a signatory, the function cannot be called and returns an error.

The offending code is found in `client/src/App.js` at line 206

### Expected behaviour
I expect that the OpenLaw API user that created a contract (by calling `apiClient.uploadContract`) should be able to access a contract's status and details (through `loadContractStatus` and `getContract`) even when that user is not a signatory.

### Environment
- OS: Ubuntu 16.04
- Openlaw-client: v0.2.3
- node: v10.15.3
- npm: 6.4.1

**Comment by outkaj** [comment]
Issue was resolved.

**Comment by jdville03** [comment]
Yes - just a few items that were cleaned up to get the upload params required to create a contract in the right format. The one to highlight would be the `creator` param which in Josh's case, we had to use the long string Id (e.g., `8f26427b-0853-469b-a4f1-132190b7373e`), but in other cases we've seen the user email to be sufficient to use as the creator Id.
