### ISSUE TITLE
Any paragraph after a list item is added as another list item

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-core#160]
*Mentioned in #bugs on Slack June 27, 2019*

If you add a list `^` (creates a `<ul><li>...</li></ul>` after parse) then any paragraph that comes after the list is embedded inside the `<ul>` as a list item. It makes reliable styles for lists in PDFs impossible.

```
^ list item
^ list item

Just some paragraph.
```

The reason we may not have noticed is because Word docs look great, and the web preview output isn't so noticeable as you can see below.

<img width="904" alt="Screen Shot 2019-06-27 at 1 24 37 PM" src="https://user-images.githubusercontent.com/1144320/60247549-96b43700-98e0-11e9-8307-28300f96470f.png">

**Comment by jdville03** [comment]
This might be a good one to prioritize for markup-language cleanup because it's been an issue for a long time and often a point of frustration with users trying to format their agreements correctly.

**Comment by outkaj** [comment]
I have a PR fix up for this. Once it gets an approving review, I'll let you know @jtrein, if you'd be interested in testing the fix out with elements etc.

**Comment by jtrein** [comment]
Sure thing! Thank you.

**Comment by outkaj** [comment]
fix has been merged and will be available in next version of ol core / client
