### ISSUE TITLE
Add Regular Expressions (or at least Contains) for Validation

### ISSUE THREAD

**Issue by jierdin** [openlawteam/openlaw-core#173]
Regex would add a lot of power to the Validation feature, however, the most common use case for text is going to be "contains" or "does not contain".
A tangible example:
A variable for the Name of a company. 
I want to make sure that this Text contains LLC OR L.L.C. OR Limited Liability Corp OR etc.
Otherwise, they are given a validation error, informing them to change the Name.

**Comment by jtrein** [comment]
Hi @jierdin, thanks for issue. Yes, we'll need to find a good way to accomplish this. We agree it is a language feature that would be good to have! I don't work in Core, but having at least a "contains" or "not contains" would seem more likely at this stage, I would assume.

cc: @craigwblake @adridadou

**Comment by adridadou** [comment]
done
