### ISSUE TITLE
Add default value for YesNo

### ISSUE THREAD

**Issue by jierdin** [openlawteam/openlaw-core#174]
YesNo, as it is, is generated as two empty radio buttons. It would be nice to be able to select a default value, to streamline the UX, or at least push  helping nudge users down the right pathways.

**Comment by jtrein** [comment]
Hi @jierdin, thank you for placing this back on our radar; we agree with you - we would like to include it in the language. Not sure when this work will kick-off.

cc: @craigwblake @adridadou

**Comment by adridadou** [comment]
now that we have the constants true/false, it should be pretty easy to do

**Comment by adridadou** [comment]
it is done in our dev env. It will be released soon!
