### ISSUE TITLE
look into using library to help with PeriodType

### ISSUE THREAD

**Issue by outkaj** [openlawteam/openlaw-core#177]
as discussed in #176 the `PeriodType` logic is getting more complicated, at some point in the future it may be useful to look into an external library we could use for the time-related (as opposed to lang-related) logic

**Comment by adridadou** [comment]
Any candidate? I would say that we should consider it only if we are missing another feature

**Comment by outkaj** [comment]
I don't have a candidate personally, what about you @craigwblake-openlaw?
