### ISSUE TITLE
Get serviceName

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-core#180]
With the advent of https://github.com/openlawteam/openlaw-app/pull/2715, it would good to explore a method for getting the `serviceName`, after it's been validated.

For example, this would be very nice for the Elements lib.

Is this possible?

cc: @fforbeck

**Comment by fforbeck** [comment]
@jtrein 
In this case you are thinking about passing the json value of the variable and extract only the service name? If so, we can do that on openlaw-client. 
qq: For Elements lib, where would we call that?

**Comment by jtrein** [comment]
Yep! Sounds good to me. We would call it as early as we know the serviceName. It could be used as a prop, or we could just call the function on render inside of ExternalSignature.

**Comment by fforbeck** [comment]
As discussed above, it will be done in ol-client. Closing.
