### ISSUE TITLE
Contract Creation date shown on OpenLaw UI does not reflect local time

### ISSUE THREAD

**Issue by javaadpatel** [openlawteam/openlaw-core#194]
Hi, small thing I've noticed, the UI does not reflec the local time of the user, see screenshot:

![image](https://user-images.githubusercontent.com/22832462/67140228-d40a4f00-f258-11e9-97ab-b24586075356.png)

**Comment by jtrein** [comment]
Moved: https://github.com/openlawteam/openlaw-issue-tracker/issues/24
