### ISSUE TITLE
Formatting: Contract PDFs render with justified text, but not for pre-signature preview

### ISSUE THREAD

**Issue by ctjlewis** [openlawteam/openlaw-core#268]
I know it's common to use justified text in legal writing, but this actually messes up the page count and introduces a few other formatting issues. It also only exists when emailed about a signed contract, and the DOCX preview pre-signature does not have this issue:

Pre-signature (docx):
![image](https://user-images.githubusercontent.com/1657236/99009296-7143bf80-250d-11eb-9629-b1f330206ba7.png)

After signature (pdf):
![image](https://user-images.githubusercontent.com/1657236/99009316-7bfe5480-250d-11eb-9606-1fa268eae6b6.png)

I'd be happy to submit a PR and adjust the logic for this if I can be directed to where it's located. Apologies if this is the wrong repo, most of the documentation seems to pertain to a much older version of the openlaw.io site and library.

**Comment by adridadou** [comment]
we've just released a new version that fixes that. Could you try again?

**Comment by ctjlewis** [comment]
You guys are awesome, thanks so much!

If you need help updating the documentation or anything else, I'd be happy to help, just shoot me an email: [christian@trytelework.com](mailto:christian@trytelework.com)
