### ISSUE TITLE
Repository documentation incorrect in README.md

### ISSUE THREAD

**Issue by wompeter** [openlawteam/openlaw-core#36]
Struggled with getting a test project going with openlaw-core.  I'm brand new to Scala and the "Getting Started" section presents some hurdles.

1.  The resolver URL listed in the README.md file ( https://openlawos.bintray.com/openlaw-core ), does not work.  The URL listed in the official docs site does work and finally got me going.

2. The syntax of  `resolvers += "https://dl.bintray.com/openlawos/openlaw-core"` doesn't work.  I can't find out if this is a typo or I'm just so new to Scala that it's a stupid obvious thing I'm not doing, but I had to use the syntax of `resolvers += "OpenLaw Core" at "https://dl.bintray.com/openlawos/openlaw-core"`.   

I can't find reference to the first syntax version, and the official scala docs seem to only support the second version.

Fixing those up would be great and save other new people hours of frustration :)

**Comment by adridadou** [comment]
sure so sorry about that! Just fixed it.
We had some issues with our previous repo and had to migrate. It should be stable now!

regarding the point 2, I don't see an issue but if you can show me the project I can take a look

**Comment by wompeter** [comment]
The error when I try to run sbt with the resolvers appending just an URL, rather than "name" at "URL", is this:

```
build.sbt:2: error: No implicit for Append.Value[Seq[sbt.librarymanagement.Resolver], String] found
,
  so String cannot be appended to Seq[sbt.librarymanagement.Resolver]
resolvers += "https://openlawos.bintray.com/openlaw-core"
          ^
[error] Type error in expression
```

<img width="1093" alt="sbt-error" src="https://user-images.githubusercontent.com/4419482/49461554-d1217f80-f7a8-11e8-85d7-8533d341a9d5.png">

The project is literally just "Hello World".  I can reproduce by just 

1.  Make new directory
2.  Run sbt
3.  Quit sbt
4.  Create `HelloWorld.scala` in src/main/scala
5.  Create `build.sbt` with the file shown in the screenshot above (literally the two lines from your README and a project settings variable declaration)
6.  Run sbt again

I'm using Scala 2.12 with vscode and Ensime, all freshly installed as per the instructions here: http://ensime.github.io/build_tools/sbt/.   Using MacOS.

**Comment by adridadou** [comment]
ok ... doing too many things at the same time doesn't work for me :)
Thanks for pointing that out I've just fixed it
