### ISSUE TITLE
Section numbers can't be cross referenced if they appear below the reference

### ISSUE THREAD

**Issue by bwiles81** [openlawteam/openlaw-core#46]
When I try to reference a section that appears below the cross reference, I get a "Section referenced before it has been rendered. The executor can't guess the section number before rendering it yet." error.

^^**Share Limit.** Subject to Section [[Additional Shares]], the aggregate number of Shares which may be issued under the Plan shall not exceed 1,000,000 Shares. The number of Shares which are subject to Options or other rights outstanding at any time shall not exceed the number of Shares which then remain available for issuance under the Plan. The Company, during the term of the Plan, shall at all times reserve and keep available sufficient Shares to satisfy the requirements of the Plan. Shares offered under the Plan may be authorized but unissued Shares or treasury Shares.

^^(Additional Shares) **Additional Shares.** In the event that any outstanding Option or other right expires or is canceled for any reason, the Shares allocable to the unexercised portion of such Option or other right shall remain available for issuance pursuant to the Plan. If a Share previously issued under the Plan is reacquired by the Company pursuant to a forfeiture provision, then such Share shall again become available for issuance under the Plan.

**Comment by jdville03** [comment]
We've finished this enhancement and you should now be able to reference a section that comes after the cross-reference.
