### ISSUE TITLE
How to call only one portion of a Date variable

### ISSUE THREAD

**Issue by bwiles81** [openlawteam/openlaw-core#47]
For example, accessing only the year of a Date variable.  (Am drafting an equity incentive plan, most equity incentive plans are named after the year they were adopted, hence the need to access the year of a Date variable.)

**Comment by craigwblake-openlaw** [comment]
We've added some new formats for the date variables; in the next release you can use `year`, `day`, `day_name`, `month`, and `month_name` to render only portions of the date variable.
