### ISSUE TITLE
Enhancement: Add getTemplateById() method to APIClient

### ISSUE THREAD

**Issue by ShayShayBeekay** [openlawteam/openlaw-core#53]
Currently to fetch templates from using the `APIClient`, we call the `getTemplate(string: templateName)` method.  In some cases we could have multiple templates with the same title, and so would need to differentiate by template id.

A method to fetch a template using the template id would be preferred, and would remove potential issued with fetching the template should the name be updated manually by an end-user. Proposed would be a method `getTemplateById(string: templateId)` or similar.

**Comment by adridadou** [comment]
it has been added! It will be available soon in the next release

**Comment by rachelob** [comment]
@adridadou has the new release been rolled out? I can't seem to use this on assetFactory.openlaw.io or app.openlaw.io

getTemplate(X) works fine:
<img width="1918" alt="screenshot 2019-01-23 at 12 36 47" src="https://user-images.githubusercontent.com/42391830/51607157-d038de80-1f0b-11e9-8d09-32b2b9bd3f50.png">

but I'm getting a 404 on getTemplateById(idOfX):
<img width="1918" alt="screenshot 2019-01-23 at 12 36 57" src="https://user-images.githubusercontent.com/42391830/51607207-fa8a9c00-1f0b-11e9-8ea5-38c807f37582.png">

**Comment by adridadou** [comment]
on the client side yes, on the server side, it's in develop and should be in production later this week
