### ISSUE TITLE
Bug: Unable to view draft template

### ISSUE THREAD

**Issue by Ro5s** [openlawteam/openlaw-core#59]
Hello, I am having trouble opening, viewing this draft template: https://app.openlaw.io/template/Proof%20of%20Claim%20Form%20(Token%20Generator)

Thank you for your assistance! 
![screen shot 2019-01-19 at 12 46 49 pm](https://user-images.githubusercontent.com/41117279/51430365-60afb000-1be8-11e9-95f9-cbad5ed33df4.png)

**Comment by Ro5s** [comment]
I might be having similar issue with this template: https://app.openlaw.io/template/LLC%20Formation%20Tkn%20Test

(Will not send contract . . . my smart contract integration might be unfriendly with OL upgrade)

**Comment by outkaj** [comment]
@Ro5s we've fixed this bug and you shouldn't have any issues in our next release (this Friday). I'm closing this for now, but don't hesitate to re-open if you still see the error after that!
